### ISSUE TITLE
`https://webserver2.tecgraf.puc-rio.br/iup/` is not accessible

### ISSUE THREAD

**Issue by chenrui333** [batiati/IUPforZig#4]
👋 looks like `https://webserver2.tecgraf.puc-rio.br/iup/` url is not accessible atm

**Comment by batiati** [comment]
Hi! Nice catch. It looks like an issue in the https, the same link works with http. I'll try to notify the responsible.

For more context, where did you found this link in this repository? It's from the readme.md?

**Comment by batiati** [comment]
Fixed by https://github.com/batiati/IUPforZig/commit/cc04fbd4a4a00607fe937c85260d013f737fa06c
